###
POST https://rgdceehryi.execute-api.localhost.localstack.cloud:4566/prod/payment
Content-Type: application/json

{
  "amount": "400",
  "status": "completed"
}

###
GET  https://rgdceehryi.execute-api.localhost.localstack.cloud:4566/prod/payment?id=19&status=completed
Content-Type: application/json

###
GET http://localhost:3000/notifications
Content-Type: application/json

